In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics as sm
from sklearn import datasets

In [5]:

iris = datasets.load_iris()
X = pd.DataFrame(iris.data,columns = iris.feature_names)
y = pd.DataFrame(iris.target,columns = ['y'])
#reshaping y
y = np.array(y).reshape(150,)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0) 


In [9]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy:",sm.accuracy_score(y_test, y_pred))
print(sm.confusion_matrix(y_test, y_pred))

Accuracy: 0.9777777777777777
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
