This is jupyter lab, which comes bundled with Anaconda package for installing python. 

**Install Robotic toolbox for python by Dr.Peter Corke :** https://github.com/petercorke/robotics-toolbox-python
Spatial math toolbox comes bundled with robotic toolbox. If there is some error try installing it separately from : https://github.com/petercorke/spatialmath-python 

Mainly there are 5 python classes based on mathematical groups which are used in this course: \SO2, \SO3, \SE2, \SE3, Unit Quaternions.
SO2 & SO3 - Rotation or Orientation group in 2D and 3D. The rotation group consists of all the rotation about origin of a 3 dimensional Euclidean space. Represents 2D and 3D rotation matrices.
SE2 & SE3 - Euclidean group in 2D and 3D. The transformations of the space that preserve the Euclidean distance between any two points. Comprises of both translation and rotation; represents Homogeneous transformation matrix.

In [1]:
from spatialmath import *
from spatialmath.base import *
import spatialmath.base.symbolic as sym
import numpy as np
from matplotlib import pyplot as plt

Matlab style command input and output is obtained from second line above.

In [2]:
R1 = rot2(0.3)

rot2 is 2D rotation matrix, Note you need only one angle to specify the 2 dimensional rotation matrix the default angle is in rad. 

In [3]:
R1

array([[ 0.95533649, -0.29552021],
       [ 0.29552021,  0.95533649]])

In [4]:
rot2(30,'deg')

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [5]:
type (R1)

numpy.ndarray

In [6]:
np.linalg.det(R1)

0.9999999999999999

In [7]:
np.transpose(R1)

array([[ 0.95533649,  0.29552021],
       [-0.29552021,  0.95533649]])

In [8]:
np.linalg.inv(R1)

array([[ 0.95533649,  0.29552021],
       [-0.29552021,  0.95533649]])

In [9]:
R1*np.transpose(R1) #elementwise multiplication

array([[ 0.91266781, -0.08733219],
       [-0.08733219,  0.91266781]])

In [10]:
R1**2

array([[0.91266781, 0.08733219],
       [0.08733219, 0.91266781]])

In [11]:
np.around(R1@np.transpose(R1)) #Composition operation 

array([[ 1., -0.],
       [-0.,  1.]])

f, g ==> h = f(g)

In [12]:
R1@R1

array([[ 0.82533561, -0.56464247],
       [ 0.56464247,  0.82533561]])

In [13]:
np.around(np.linalg.det(R1@R1))

1.0

In [109]:
theta = sym.symbol('theta')

In [110]:
R2 = rot2(theta)

In [16]:
R2

array([[cos(theta), -sin(theta)],
       [sin(theta), cos(theta)]], dtype=object)

In [111]:
R2*R2

array([[cos(theta)**2, sin(theta)**2],
       [sin(theta)**2, cos(theta)**2]], dtype=object)

In [18]:
R2@R2

array([[-sin(theta)**2 + cos(theta)**2, -2*sin(theta)*cos(theta)],
       [2*sin(theta)*cos(theta), -sin(theta)**2 + cos(theta)**2]],
      dtype=object)

In [113]:
sym.simplify(R2@R2)

[[cos(2*theta), -sin(2*theta)], [sin(2*theta), cos(2*theta)]]

In [20]:
sym.simplify(np.transpose(R2@R2))

[[cos(2*theta), sin(2*theta)], [-sin(2*theta), cos(2*theta)]]

np.linalg doesnot seem to work with symbolic representations.

**2D** 

In [21]:
transl2(1,2) #matlab style

array([[1., 0., 1.],
       [0., 1., 2.],
       [0., 0., 1.]])

In [22]:
SE2(1,2)

   1         0         1         
   0         1         2         
   0         0         1         


In [23]:
SE2(30,unit='deg')

   0.866    -0.5       0         
   0.5       0.866     0         
   0         0         1         


In [24]:
T1 = SE2(1,2)*SE2(30,unit='deg') #The FAR convention

In [25]:
type(T1)

spatialmath.pose2d.SE2

In [26]:
T1

   0.866    -0.5       1         
   0.5       0.866     2         
   0         0         1         


In [27]:
T2 = SE2(2,1)

In [28]:
T2

   1         0         2         
   0         1         1         
   0         0         1         


In [29]:
T3 = T2*T1

In [30]:
T3

   0.866    -0.5       3         
   0.5       0.866     3         
   0         0         1         


In [31]:
T3 = T1*T2

In [32]:
T3 #The translations happens first and then the rotation

   0.866    -0.5       2.232     
   0.5       0.866     3.866     
   0         0         1         


In [33]:
T1.inv()

   0.866     0.5      -1.866     
  -0.5       0.866    -1.232     
   0         0         1         


![alt text](homog_inv.png "T inverse")

In [34]:
x = sym.symbol('x')
y = sym.symbol('y')

In [35]:
Ts1 = SE2(x,y)*SE2(theta)

In [36]:
Ts1

  cos(theta)   -sin(theta)  x             
  sin(theta)   cos(theta)   y             
  0            0             1         


# 3D rotations and Euler angles

In [37]:
R_x = SO3.Rx(30,unit='deg')

In [38]:
R_x

   1         0         0         
   0         0.866    -0.5       
   0         0.5       0.866     


In [39]:
R_y = SO3.Ry(45, unit='deg')

In [40]:
R_y

   0.7071    0         0.7071    
   0         1         0         
  -0.7071    0         0.7071    


In [41]:
R_z = SO3.Rz(60)

In [42]:
R_z

  -0.9524    0.3048    0         
  -0.3048   -0.9524    0         
   0         0         1         


In [43]:
R_z = SO3.Rz(60,unit='deg')

In [44]:
R_z

   0.5      -0.866     0         
   0.866     0.5       0         
   0         0         1         


In [45]:
R_x@R_y@R_z

   0.3536   -0.6124    0.7071    
   0.9268    0.1268   -0.3536    
   0.1268    0.7803    0.6124    


In [46]:
R_x*R_y*R_z

   0.3536   -0.6124    0.7071    
   0.9268    0.1268   -0.3536    
   0.1268    0.7803    0.6124    


In [47]:
R_eul = SO3.Rz(0.3)*SO3.Ry(0.45)*SO3.Rz(0.6)

In [48]:
R_eul

   0.5431   -0.7296    0.4155    
   0.759     0.6382    0.1285    
  -0.359     0.2456    0.9004    


In [49]:
sym.simplify(np.linalg.eig(R_eul.R))

([0.5408919826731 + 0.841092065757348*I, 0.5408919826731 - 0.841092065757348*I, 1.0], [[0.705392651746975, 0.705392651746975, 0.0695874537739475], [-0.0227109493025562 - 0.627284235437685*I, -0.0227109493025562 + 0.627284235437685*I, 0.460431755536335], [-0.0436511127366459 + 0.326365574121044*I, -0.0436511127366459 - 0.326365574121044*I, 0.884963380468925]])

In [50]:
R_eul.eul()

array([0.3 , 0.45, 0.6 ])

In [51]:
R_eul = SO3.Rz(0.1)*SO3.Ry(-0.2)*SO3.Rz(0.3)

In [52]:
R_eul

   0.9021   -0.3836   -0.1977    
   0.3875    0.9216   -0.01983   
   0.1898   -0.05871   0.9801    


In [53]:
R_eul.eul() #Non unique mapping of Euler angles to R matrix

array([-3.04159265,  0.2       , -2.84159265])

Let's put Beta = 0 in ZYZ Euler angles

In [54]:
R_eul = SO3.Rz(0.1)*SO3.Ry(0)*SO3.Rz(0.3)

In [55]:
R_eul

   0.9211   -0.3894    0         
   0.3894    0.9211    0         
   0         0         1         


In [56]:
R_eul.eul()

array([0. , 0. , 0.4])

At singularity of the Euler angles ZYZ **($\beta = 0$)**, equation reduces to the function of **($\alpha + \gamma$)**. The combinations are infinite. Therefore **$\alpha$** will be put to **zero** in the program and $\gamma$ is found out.

# Roll-Pitch-Yaw Angles

In [57]:
R_rpy = SO3.RPY(0.3,0.5,0.4) #ZYX (FAR) rotations - roll-pitch-yaw

In [58]:
R_rpy

   0.8083   -0.2415    0.5369    
   0.3417    0.9351   -0.09383   
  -0.4794    0.2593    0.8384    


In [59]:
R_rpy.rpy()

array([0.3, 0.5, 0.4])

In [60]:
R_rpy = SO3.RPY(0.5,np.pi/2,0.4)

In [61]:
R_rpy

   0         0.09983   0.995     
   0         0.995    -0.09983   
  -1         0         0         


In [62]:
R_rpy.rpy()

array([ 0.        ,  1.57079633, -0.1       ])

Notice here also $\alpha$ is 0. The $\beta = \pi/2$ value is a singular value for RPY. Rotation matrix becomes function of $\alpha$ and $\gamma$ alone. $\alpha$ set to zero.

# Axis-angle Conversion

In [63]:
R_rpy = rpy2r(0.5,0.3,0.4)

In [64]:
[theta, v] = tr2angvec(R_rpy) #list unpacking

In [65]:
theta

0.6585264597095669

In [66]:
v

array([0.65250189, 0.5891706 , 0.47657034])

According to Fixed point Theorom by Euler:

![alt text](Euler_FPT.png "T inverse")

In [67]:
[x,e] = np.linalg.eig(R_rpy)

In [68]:
sym.simplify(x)

[0.790894825891343 + 0.611952101375837*I, 0.790894825891343 - 0.611952101375837*I, 1.0]

In [69]:
sym.simplify(e)

[[-0.250113738017652 - 0.473881588762976*I, -0.250113738017652 + 0.473881588762976*I, 0.652501889478207], [-0.225837908069098 + 0.524820197621507*I, -0.225837908069098 - 0.524820197621507*I, 0.589170602538001], [0.621643271767508, 0.621643271767508, 0.476570336185938]]

*The column corresponding to* **eigen value equal 1** gives the vector about which rotation is happening **(3rd column).**

Angle is given by trace(R_rpy) = $1+2\cos\theta$. But this formulae does not give the indication of sign.

In [70]:
np.arccos((np.trace(R_rpy) - 1)/2)

0.6585264597095668

# Unit Quaternions

In [71]:
q = UnitQuaternion(SO3.RPY(0.1,0.2,0.3))

In [72]:
q

 0.9833 <<  0.0343,  0.1060,  0.1436 >>


For a quaternion q, $a^2+b^2+c^2+d^2$ = 1. In the toolbox quaternion is represented by and the normalization constant followed by the vector part inside double angular bracket. a << b,c,d >>. 

In [73]:
q_mul = q*q

In [74]:
q_mul #Hamiltonian Product

 0.9339 <<  0.0674,  0.2085,  0.2824 >>


In [75]:
q.inv()

 0.9833 << -0.0343, -0.1060, -0.1436 >>


In [76]:
q*q.inv()

 1.0000 <<  0.0000,  0.0000,  0.0000 >>


In [77]:
q/q

 1.0000 <<  0.0000,  0.0000,  0.0000 >>


In [78]:
q.R

array([[ 0.93629336, -0.27509585,  0.21835066],
       [ 0.28962948,  0.95642509, -0.03695701],
       [-0.19866933,  0.0978434 ,  0.97517033]])

In [79]:
qvmul([0,1,0,0],[1,2,3])

array([ 1., -2., -3.])

In [80]:
q.vec

array([0.98334744, 0.0342708 , 0.10602051, 0.14357218])

In [81]:
qvmul(q.vec,[1,2,3])

array([1.04115366, 2.09160861, 2.92252844])

In [82]:
q.angvec()

(0.3655021863566987, array([0.18857511, 0.58337798, 0.79000605]))

In [83]:
1 - (0.256**2 + 0.343**2)

0.816815

In [84]:
np.sqrt(0.816815)

0.9037781807501218

In [85]:
0.256**2 + 0.343**2 + 0.904**2

1.000401

In [86]:
q = [np.cos(60*np.pi/180), 0.256*np.sin(60*np.pi/180),0.343*np.sin(60*np.pi/180),0.904*np.sin(60*np.pi/180)]

In [87]:
q = UnitQuaternion(q)

In [88]:
q.vec

array([0.49992483, 0.22166917, 0.29700206, 0.78276926])

In [89]:
qvmul(q.vec,[1,3,5])

array([0.86513173, 1.15979589, 5.73641182])

In [90]:
np.cos(60*np.pi/180)

0.5000000000000001

In [91]:
q

 0.4999 <<  0.2217,  0.2970,  0.7828 >>


In [92]:
q.R

array([[-0.40187589, -0.65097918,  0.64398903],
       [ 0.91432398, -0.32372989,  0.24333231],
       [ 0.05007423,  0.68660401,  0.72530511]])

In [93]:
sym.simplify(np.linalg.eig(q.R))

([-0.500150329788315 + 0.86593859344219*I, -0.500150329788315 - 0.86593859344219*I, 1.0], [[0.683553315185425, 0.683553315185425, 0.25594868743174], [-0.0642033336361956 - 0.661118000903963*I, -0.0642033336361956 + 0.661118000903963*I, 0.342931249176119], [-0.169212284568865 + 0.250844551227942*I, -0.169212284568865 - 0.250844551227942*I, 0.903818802493329]])

In [94]:
np.arccos((np.trace(q.R)-1)/2)*180/np.pi

120.0099462372171

In [95]:
np.cos(60*np.pi/180)

0.5000000000000001

In [96]:
R1 = SO3.RPY([60,20,0],unit='deg')

In [97]:
R1

   0.9397    0.2962    0.171     
   0         0.5      -0.866     
  -0.342     0.8138    0.4698    


In [98]:
np.trace(R1.R)

1.9095389311788629

In [99]:
sym.simplify(np.linalg.eig(R1.R))

([1.0, 0.454769465589432 + 0.890609192164276*I, 0.454769465589432 - 0.890609192164276*I], [[0.943075312894348, 0.112456798774685 - 0.206538000169373*I, 0.112456798774685 + 0.206538000169373*I], [0.288022074947253, 0.0343451260807619 + 0.676270696160965*I, 0.0343451260807619 - 0.676270696160965*I], [-0.166289622503351, 0.697261701747519, 0.697261701747519]])

In [100]:
theta = np.arccos((np.trace(R1.R)-1)/2)

In [101]:
theta

1.0986829800264375

In [102]:
R1.angvec()

(1.0986829800264375, array([ 0.94307531,  0.28802207, -0.16628962]))

In [103]:
q = UnitQuaternion([np.cos(theta), 0.943*np.sin(theta), 0.288*np.sin(theta), -0.166*np.sin(theta)])

In [104]:
q

 0.4548 <<  0.8399,  0.2565, -0.1479 >>


In [105]:
q.vec

array([ 0.45481474,  0.83992808,  0.25652098, -0.14785584])

In [106]:
qvmul(q.vec,[1,3,5])

array([ 2.44572093, -5.2670169 , -1.13003631])

In [107]:
R1*[1,3,5]

array([[ 2.68333738],
       [-2.83012702],
       [ 4.44860445]])