# Part 1

In [55]:
import spatialmath
from spatialmath import *
from spatialmath.base import *
from spatialmath.base import symbolic as sym
import numpy as np
from matplotlib import pyplot as plt

In [56]:
#Q1

R_x = rotx(30,unit='deg')
print("Rx\n",R_x)

R_z = rotz(45, unit='deg')
print("Rz\n",R_z)

R = R_z@R_x 
print("R\n",R)
print()

Bp =np.array([[-5],[5],[5]])
print("Bp\n",Bp)

Ap = R@Bp
print()
print("Ap\n",Ap)

Rx
 [[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]
Rz
 [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
R
 [[ 0.70710678 -0.61237244  0.35355339]
 [ 0.70710678  0.61237244 -0.35355339]
 [ 0.          0.5         0.8660254 ]]

Bp
 [[-5]
 [ 5]
 [ 5]]

Ap
 [[-4.82962913]
 [-2.24143868]
 [ 6.83012702]]


In [57]:
#Q2

R_y = SO3.Ry(30,unit='deg')
R_x = SO3.Rx(30, unit='deg')

R=R_x @ R_y
print(R)
Rt = np.transpose(R)
print(Rt)

Ap = np.array([[3],[5],[3]])
Bp = Rt @ Ap
print(Bp)

   0.866     0         0.5       
   0.25      0.866    -0.433     
  -0.433     0.5       0.75      

[[ 0.8660254  0.25      -0.4330127]
 [ 0.         0.8660254  0.5      ]
 [ 0.5       -0.4330127  0.75     ]]
[[2.54903811]
 [5.83012702]
 [1.58493649]]


In [58]:
#Q3

R_x = rotx(45,unit='deg')
R_z = rotz(60, unit='deg')
R = R_x@R_z
print(R)

Bp =np.array([[-10],[10],[10]])
Ap = R@Bp
Ap

[[ 0.5        -0.8660254   0.        ]
 [ 0.61237244  0.35355339 -0.70710678]
 [ 0.61237244  0.35355339  0.70710678]]


array([[-13.66025404],
       [ -9.65925826],
       [  4.48287736]])

In [59]:
#Q4

R_z = SO3.Rz(60,unit='deg')
R_x = SO3.Rx(30, unit='deg')
R = R_z @ R_x

Rt = np.linalg.inv(R)

print()
Ap = np.array([[4],[4],[3]])
Bp =Rt@Ap
print(Bp)


[[5.46410162]
 [0.23205081]
 [3.33012702]]


In [60]:
#Q5

R_x = rotx(45,unit='deg')  
R_y = roty(60,unit='deg') 
R_z = rotz(30, unit='deg')
q = np.array([[-3],[3],[6]])

R = R_x @ R_y @ R_z
t = np.c_[R, q]
T = np.r_[t, [np.array([0,0,0,1])]] 
print(T)
print()

#now for the inverse homogenous transformation matrix
RT = np.transpose(R)
a = -RT @ q
print(a)
print()

T = np.c_[RT, -RT @ q]
T = np.r_[T, [np.array([0,0,0,1])]] 
print(T)

[[ 0.4330127  -0.25        0.8660254  -3.        ]
 [ 0.88388348  0.30618622 -0.35355339  3.        ]
 [-0.1767767   0.91855865  0.35355339  6.        ]
 [ 0.          0.          0.          1.        ]]

[[-0.29195215]
 [-7.17991057]
 [ 1.53741604]]

[[ 0.4330127   0.88388348 -0.1767767  -0.29195215]
 [-0.25        0.30618622  0.91855865 -7.17991057]
 [ 0.8660254  -0.35355339  0.35355339  1.53741604]
 [ 0.          0.          0.          1.        ]]


In [61]:
#Q6

R_Y = SO3.Ry(60,unit='deg')  
R_y = SO3.Ry(30,unit='deg') 
R_z = SO3.Rz(45, unit='deg')
q = np.array([[1],[2],[-3]])
R = R_Y @ R_z @ R_y
print(R)
print()

T = np.c_[R, q]
T = np.r_[T, [np.array([0,0,0,1])]] 
print(T)
print()

Bp =np.array([[1],[2],[1],[1]])
Ap = T@Bp
print(Ap[:3])

  -0.1268   -0.3536    0.9268    
   0.6124    0.7071    0.3536    
  -0.7803    0.6124    0.1268    


[[-0.12682648 -0.35355339  0.9267767   1.        ]
 [ 0.61237244  0.70710678  0.35355339  2.        ]
 [-0.78033009  0.61237244  0.12682648 -3.        ]
 [ 0.          0.          0.          1.        ]]

[[ 1.09284343]
 [ 4.38013939]
 [-2.42875873]]


In [62]:
#Q7

R_x = SO3.Rx(90,unit='deg') 
R_z = SO3.Rz(45, unit='deg')
q = np.array([[2],[3],[1]])
R = R_z @ R_x           
print(R)
print()
    
t = np.c_[R, q]
T = np.r_[t, [np.array([0,0,0,1])]]
print(T)
print()

Ap = np.array([[2],[2],[3],[1]])
Bp = np.linalg.inv(T)@Ap
print(Bp[:3])

   0.7071    0         0.7071    
   0.7071    0        -0.7071    
   0         1         0         


[[ 7.07106781e-01 -4.32978028e-17  7.07106781e-01  2.00000000e+00]
 [ 7.07106781e-01  4.32978028e-17 -7.07106781e-01  3.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[-0.70710678]
 [ 2.        ]
 [ 0.70710678]]


In [63]:
#Q8

R_y = roty(60,unit='deg') 
R_z = rotz(30, unit='deg')
q = np.array([[-3],[3],[-1]])
R = R_y @ R_z
print(R)
print()

T = np.c_[R, q]
T = np.r_[T, [np.array([0,0,0,1])]]
print(T)
print()

Ap = np.array([[2],[2],[1],[1]])
Bp = np.linalg.inv(T)@Ap
print(Bp[:3])

[[ 0.4330127 -0.25       0.8660254]
 [ 0.5        0.8660254  0.       ]
 [-0.75       0.4330127  0.5      ]]

[[ 0.4330127 -0.25       0.8660254 -3.       ]
 [ 0.5        0.8660254  0.         3.       ]
 [-0.75       0.4330127  0.5       -1.       ]
 [ 0.         0.         0.         1.       ]]

[[ 0.16506351]
 [-1.25      ]
 [ 5.33012702]]


In [64]:
#Q9

sym.simplify(np.linalg.eigvals(SO2(45,unit='deg')))

[0.707106781186548 + 0.707106781186547*I, 0.707106781186548 - 0.707106781186547*I]

In [65]:
#Q10

sym.simplify(np.linalg.eigvals(rotx(30,unit='deg'))) 

[0.866025403784439 + 0.5*I, 0.866025403784439 - 0.5*I, 1.0]

# Part 2

#### Q1 Finding Alpha,Beta,Gamma

In [66]:
import numpy as np
import spatialmath.base.symbolic as sym
from numpy import linalg as ln
from spatialmath.base import *
from spatialmath import *
from sympy import *

T = Symbol('θ') # theta is a symbolic variable
r = Matrix(rot2(T)).eigenvals()
print(r)

r= rot2(45, 'deg')

e,v = np.linalg.eig(r)

print('\n')
print(e)

T = Symbol('θ')
r = Matrix(rotx(T)).eigenvals()
print(tuple(e))

R = rotx(30,'deg')
e,v = np.linalg.eig(R)
print('θ = 30 degrees')
print(list(e))

{-sqrt((cos(θ) - 1)*(cos(θ) + 1)) + cos(θ): 1, sqrt((cos(θ) - 1)*(cos(θ) + 1)) + cos(θ): 1}


[0.70710678+0.70710678j 0.70710678-0.70710678j]
((0.7071067811865476+0.7071067811865475j), (0.7071067811865476-0.7071067811865475j))
θ = 30 degrees
[(0.8660254037844387+0.4999999999999999j), (0.8660254037844387-0.4999999999999999j), (1+0j)]


### Question 2

In [67]:
a = sym.symbol('α')
b = sym.symbol('β')
c = sym.symbol('γ')

#More of a formula view
rpy_matrix = np.matrix(rpy2r(a,b,c))
#print(rpy_matrix)

#input with actual values

rpy_matrix = np.matrix(rpy2r(a,-90,c,unit='deg'))
print(rpy_matrix)


[[6.12323399573677e-17*cos(0.0174532925199433*γ)
  -1.0*sin(0.0174532925199433*α)*cos(0.0174532925199433*γ) - 1.0*sin(0.0174532925199433*γ)*cos(0.0174532925199433*α)
  1.0*sin(0.0174532925199433*α)*sin(0.0174532925199433*γ) - 1.0*cos(0.0174532925199433*α)*cos(0.0174532925199433*γ)]
 [6.12323399573677e-17*sin(0.0174532925199433*γ)
  -1.0*sin(0.0174532925199433*α)*sin(0.0174532925199433*γ) + 1.0*cos(0.0174532925199433*α)*cos(0.0174532925199433*γ)
  -1.0*sin(0.0174532925199433*α)*cos(0.0174532925199433*γ) - 1.0*sin(0.0174532925199433*γ)*cos(0.0174532925199433*α)]
 [1.0 6.12323399573677e-17*sin(0.0174532925199433*α)
  6.12323399573677e-17*cos(0.0174532925199433*α)]]


### Question 3

In [68]:
a = sym.symbol('α')
b = sym.symbol('β')
c = sym.symbol('γ')

rpy_zyx = SO3.RPY(a,np.pi/2,c)
print(rpy_zyx)
print()

rpy_zyz = SO3.Rz(a)*SO3.Ry(np.pi/2)*SO3.Rz(c)
print(rpy_zyz)

  6.12323399573677e-17*cos(γ) 1.0*sin(α)*cos(γ) - 1.0*sin(γ)*cos(α) 1.0*sin(α)*sin(γ) + 1.0*cos(α)*cos(γ)  
  6.12323399573677e-17*sin(γ) 1.0*sin(α)*sin(γ) + 1.0*cos(α)*cos(γ) -1.0*sin(α)*cos(γ) + 1.0*sin(γ)*cos(α)  
  -1        6.12323399573677e-17*sin(α) 6.12323399573677e-17*cos(α)  


  -1.0*sin(α)*sin(γ) + 6.12323399573677e-17*cos(α)*cos(γ) -1.0*sin(α)*cos(γ) - 6.12323399573677e-17*sin(γ)*cos(α) 1.0*cos(α)    
  6.12323399573677e-17*sin(α)*cos(γ) + 1.0*sin(γ)*cos(α) -6.12323399573677e-17*sin(α)*sin(γ) + 1.0*cos(α)*cos(γ) 1.0*sin(α)    
  -1.0*cos(γ)  1.0*sin(γ)    0         



### Question 5

In [69]:
theta = sym.symbol('theta')
v1 = sym.symbol('v1')
v2 = sym.symbol('v2')
v3 = sym.symbol('v3')

a = sym.cos(theta/2)
b = v1*sym.sin(theta/2)
c = v2*sym.sin(theta/2)
d = v3*sym.sin(theta/2)

q1 = UnitQuaternion([np.cos(-45*np.pi/180),0.256*np.sin(-60*np.pi/180),0.343*np.sin(-30*np.pi/180),0.904*np.sin(-30*np.pi/180)])
print(q1)

q2 = UnitQuaternion([np.cos(150*np.pi/180),0.256*np.sin(150*np.pi/180),0.343*np.sin(150*np.pi/180),0.904*np.sin(150*np.pi/180)])
print(q2)

if q1 == q2:
    print("Q1 and q2 are equal and obeys equality")


 0.7992 << -0.2506, -0.1938, -0.5109 >>
 0.8660 << -0.1280, -0.1715, -0.4520 >>


### Question 6

In [70]:
v = [5 , 7 ,9]
ham_prod = SO3.Rx(30,unit='deg')
print("The Hamiltonian product is :")
print(ham_prod)
q_mul = UnitQuaternion.Rx(30,"deg")*v
print("The Quaternion multiplication is : ")
print(q_mul)

The Hamiltonian product is :
   1         0         0         
   0         0.866    -0.5       
   0         0.5       0.866     

The Quaternion multiplication is : 
[ 5.          1.56217783 11.29422863]


##### Part B

### Question 1

In [95]:
x = sym.symbol('x')

rpy_matrix = np.matrix([[0.4,x,x],[0.138,x,x],[-0.906,0.224,0.358]])
print(rpy_matrix)
print()

transform_matrix_2_rpy_angles = tr2rpy(rpy_matrix)
print(transform_matrix_2_rpy_angles)
print()

new_rpy_matrix = rpy2r(transform_matrix_2_rpy_angles)
print(new_rpy_matrix)

[[0.4 x x]
 [0.138 x x]
 [-0.906 0.224 0.358]]

[0.55910132 1.13386475 0.33221355]

[[ 0.400024    0.17783971  0.899085  ]
 [ 0.13800828  0.95811947 -0.25091989]
 [-0.90605436  0.22445515  0.35872743]]


### Question 2

In [72]:
y = sym.symbol('y')
b = sym.symbol('b')
c = sym.symbol('r')

R = np.matrix([[-0.82,y,0],[y,y,y],[y,y,-1]])
print(R)
print()
R1 = SO3.Rz(0,unit='deg')*SO3.Ry(b)*SO3.Rz(c)
print(R1)
rpy2r(0,3.14,0.609)


[[-0.82 y 0]
 [y y y]
 [y y -1]]

  1.0*cos(b)*cos(r) -1.0*sin(r)*cos(b) 1.0*sin(b)    
  1.0*sin(r)   1.0*cos(r)   0             
  -1.0*sin(b)*cos(r) 1.0*sin(b)*sin(r) 1.0*cos(b)    



array([[-8.20219435e-01, -5.72047526e-01,  1.30632653e-03],
       [-5.72046800e-01,  8.20220475e-01,  9.11073160e-04],
       [-1.59265292e-03,  0.00000000e+00, -9.99998732e-01]])

### Question 3

In [73]:
import math

R = np.matrix([[0.333,0.9107,0.2440],
                [-0.2440,0.3333,0.9107],
                [-0.9107,0.2440,0.3333]])

[x,e] = np.linalg.eig(R)
print(x)
print()
print(e)
print()

axis_angle = math.acos((np.trace(R)-1)/2)
print(axis_angle)
print()

q = UnitQuaternion(rpy2r(axis_angle,axis_angle,axis_angle))
print(q)

[ 0.75113617+0.86384182j  0.75113617-0.86384182j -0.50267233+0.j        ]

[[ 0.63274431+0.j          0.63274431-0.j          0.45224126+0.j        ]
 [ 0.32270043+0.46145198j  0.32270043-0.46145198j -0.59338508+0.j        ]
 [-0.12012297+0.51781427j -0.12012297-0.51781427j  0.66586184+0.j        ]]

1.57099632679623

 0.7071 << -0.0001,  0.7071, -0.0001 >>


### Question 4

In [94]:

#globally coordinates of the vertex F
F = np.matrix([[1.0000],
                [0.0000],
                [0.0000]])

print("Position of the vertex F before rotation is :")
print(F)
print()

#rotation matrix corresponding to rotation of the cube about its solid diagonal All by 90° in the counterclockwise direction
R = np.matrix([[np.cos(90),-np.sin(90),0.0000],
                [np.sin(90),np.cos(90),0.0000],
                [0.0000,0.0000,1.0000]])
print("Rotation Matrix is :")
print(R)
print()

#global coordinates of the vertex F after the rotation
#f1 = inverse of R * F
F1 = R.I*F
print("Position of the vertex F after rotation is :")
print(F1)

#rotation about the x-axis by 90° in the counterclockwise direction
R1 = np.matrix([[1.0000,0.0000,0.0000],
                [0.0000,0.0000,-1.0000],
                [0.0000,1.0000,0.0000]])

#rotation about the y-axis by 90° in the counterclockwise direction
R2 = np.matrix([[0.0000,0.0000,1.0000],
                [0.0000,1.0000,0.0000],
                [-1.0000,0.0000,0.0000]])

#rotation about the z-axis by 90° in the counterclockwise direction
R3 = np.matrix([[0.0000,-1.0000,0.0000],
                [1.0000,0.0000,0.0000],
                [0.0000,0.0000,1.0000]])

#making z axis rotation in clockwise direction to set F in the same place
R4 = np.matrix([[0.0000,1.0000,0.0000],
                [-1.0000,0.0000,0.0000],
                [0.0000,0.0000,1.0000]])
                
R5 = np.matrix([[0.0000,0.0000,-1.0000],
                [0.0000,1.0000,0.0000],
                [1.0000,0.0000,0.0000]])

#rotating in axis in such a way that the F comes to the same place
F2 = R1*R2*R3*R4*R5*F

print("Position of the vertex F after doing elementry rotations is :")
print(F2)

Position of the vertex F before rotation is :
[[1.]
 [0.]
 [0.]]

Rotation Matrix is :
[[-0.44807362 -0.89399666  0.        ]
 [ 0.89399666 -0.44807362  0.        ]
 [ 0.          0.          1.        ]]

Position of the vertex F after rotation is :
[[-0.44807362]
 [-0.89399666]
 [ 0.        ]]
Position of the vertex F after doing elementry rotations is :
[[1.]
 [0.]
 [0.]]
