# Q1 Finding Alpha,Beta,Gamma

In [2]:
import numpy as np
import spatialmath.base.symbolic as sym
from numpy import linalg as ln
from spatialmath.base import *
from spatialmath import *
from sympy import *

T = Symbol('θ') # theta is a symbolic variable
r = Matrix(rot2(T)).eigenvals()
print(r)

r= rot2(45, 'deg')

e,v = np.linalg.eig(r)

print('\n')
print(e)

T = Symbol('θ')
r = Matrix(rotx(T)).eigenvals()
print(tuple(e))

R = rotx(30,'deg')
e,v = np.linalg.eig(R)
print('θ = 30 degrees')
print(list(e))

{-sqrt((cos(θ) - 1)*(cos(θ) + 1)) + cos(θ): 1, sqrt((cos(θ) - 1)*(cos(θ) + 1)) + cos(θ): 1}


[0.70710678+0.70710678j 0.70710678-0.70710678j]
((0.7071067811865476+0.7071067811865475j), (0.7071067811865476-0.7071067811865475j))
θ = 30 degrees
[(0.8660254037844387+0.4999999999999999j), (0.8660254037844387-0.4999999999999999j), (1+0j)]


# Question 2

In [3]:
a = sym.symbol('α')
b = sym.symbol('β')
c = sym.symbol('γ')

#More of a formula view
rpy_matrix = np.matrix(rpy2r(a,b,c))
#print(rpy_matrix)

#input with actual values

rpy_matrix = np.matrix(rpy2r(a,-90,c,unit='deg'))
print(rpy_matrix)


[[6.12323399573677e-17*cos(0.0174532925199433*γ)
  -1.0*sin(0.0174532925199433*α)*cos(0.0174532925199433*γ) - 1.0*sin(0.0174532925199433*γ)*cos(0.0174532925199433*α)
  1.0*sin(0.0174532925199433*α)*sin(0.0174532925199433*γ) - 1.0*cos(0.0174532925199433*α)*cos(0.0174532925199433*γ)]
 [6.12323399573677e-17*sin(0.0174532925199433*γ)
  -1.0*sin(0.0174532925199433*α)*sin(0.0174532925199433*γ) + 1.0*cos(0.0174532925199433*α)*cos(0.0174532925199433*γ)
  -1.0*sin(0.0174532925199433*α)*cos(0.0174532925199433*γ) - 1.0*sin(0.0174532925199433*γ)*cos(0.0174532925199433*α)]
 [1.0 6.12323399573677e-17*sin(0.0174532925199433*α)
  6.12323399573677e-17*cos(0.0174532925199433*α)]]


# Question 3

In [4]:
a = sym.symbol('α')
b = sym.symbol('β')
c = sym.symbol('γ')

rpy_zyx = SO3.RPY(a,np.pi/2,c)
print(rpy_zyx)
print()

rpy_zyz = SO3.Rz(a)*SO3.Ry(np.pi/2)*SO3.Rz(c)
print(rpy_zyz)

  6.12323399573677e-17*cos(γ) 1.0*sin(α)*cos(γ) - 1.0*sin(γ)*cos(α) 1.0*sin(α)*sin(γ) + 1.0*cos(α)*cos(γ)  
  6.12323399573677e-17*sin(γ) 1.0*sin(α)*sin(γ) + 1.0*cos(α)*cos(γ) -1.0*sin(α)*cos(γ) + 1.0*sin(γ)*cos(α)  
  -1        6.12323399573677e-17*sin(α) 6.12323399573677e-17*cos(α)  


  -1.0*sin(α)*sin(γ) + 6.12323399573677e-17*cos(α)*cos(γ) -1.0*sin(α)*cos(γ) - 6.12323399573677e-17*sin(γ)*cos(α) 1.0*cos(α)    
  6.12323399573677e-17*sin(α)*cos(γ) + 1.0*sin(γ)*cos(α) -6.12323399573677e-17*sin(α)*sin(γ) + 1.0*cos(α)*cos(γ) 1.0*sin(α)    
  -1.0*cos(γ)  1.0*sin(γ)    0         



# Question 5

In [5]:
theta = sym.symbol('theta')
v1 = sym.symbol('v1')
v2 = sym.symbol('v2')
v3 = sym.symbol('v3')

a = sym.cos(theta/2)
b = v1*sym.sin(theta/2)
c = v2*sym.sin(theta/2)
d = v3*sym.sin(theta/2)

q1 = UnitQuaternion([np.cos(-45*np.pi/180),0.256*np.sin(-60*np.pi/180),0.343*np.sin(-30*np.pi/180),0.904*np.sin(-30*np.pi/180)])
print(q1)

q2 = UnitQuaternion([np.cos(150*np.pi/180),0.256*np.sin(150*np.pi/180),0.343*np.sin(150*np.pi/180),0.904*np.sin(150*np.pi/180)])
print(q2)

if q1 == q2:
    print("Q1 and q2 are equal and obeys equality")


 0.7992 << -0.2506, -0.1938, -0.5109 >>
 0.8660 << -0.1280, -0.1715, -0.4520 >>


# Question 6

In [6]:
v = [5 , 7 ,9]
ham_prod = SO3.Rx(30,unit='deg')
print("The Hamiltonian product is :")
print(ham_prod)
q_mul = UnitQuaternion.Rx(30,"deg")*v
print("The Quaternion multiplication is : ")
print(q_mul)

The Hamiltonian product is :
   1         0         0         
   0         0.866    -0.5       
   0         0.5       0.866     

The Quaternion multiplication is : 
[ 5.          1.56217783 11.29422863]


## Part B

### Question 1

In [7]:
x = sym.symbol('x')

rpy_matrix = np.matrix([[0.4,x,x],[0.138,x,x],[-0.906,0.224,0.358]])
print(rpy_matrix)
print()

transform_matrix_2_rpy_angles = tr2rpy(rpy_matrix)
print(transform_matrix_2_rpy_angles)
print()

new_rpy_matrix = rpy2r(transform_matrix_2_rpy_angles)

[[0.4 x x]
 [0.138 x x]
 [-0.906 0.224 0.358]]

[0.55910132 1.13386475 0.33221355]



# Question 2

In [8]:
y = sym.symbol('y')
b = sym.symbol('b')
c = sym.symbol('r')

R = np.matrix([[-0.82,y,0],[y,y,y],[y,y,-1]])
print(R)
print()
R1 = SO3.Rz(0,unit='deg')*SO3.Ry(b)*SO3.Rz(c)
print(R1)
rpy2r(0,3.14,0.609)


[[-0.82 y 0]
 [y y y]
 [y y -1]]

  1.0*cos(b)*cos(r) -1.0*sin(r)*cos(b) 1.0*sin(b)    
  1.0*sin(r)   1.0*cos(r)   0             
  -1.0*sin(b)*cos(r) 1.0*sin(b)*sin(r) 1.0*cos(b)    



array([[-8.20219435e-01, -5.72047526e-01,  1.30632653e-03],
       [-5.72046800e-01,  8.20220475e-01,  9.11073160e-04],
       [-1.59265292e-03,  0.00000000e+00, -9.99998732e-01]])

# Question 3

In [9]:
import math

R = np.matrix([[0.333,0.9107,0.2440],
                [-0.2440,0.3333,0.9107],
                [-0.9107,0.2440,0.3333]])

[x,e] = np.linalg.eig(R)
print(x)
print()
print(e)
print()

axis_angle = math.acos((np.trace(R)-1)/2)
print(axis_angle)
print()

q = UnitQuaternion(rpy2r(axis_angle,axis_angle,axis_angle))
print(q)

[ 0.75113617+0.86384182j  0.75113617-0.86384182j -0.50267233+0.j        ]

[[ 0.63274431+0.j          0.63274431-0.j          0.45224126+0.j        ]
 [ 0.32270043+0.46145198j  0.32270043-0.46145198j -0.59338508+0.j        ]
 [-0.12012297+0.51781427j -0.12012297-0.51781427j  0.66586184+0.j        ]]

1.57099632679623

 0.7071 << -0.0001,  0.7071, -0.0001 >>


# Question 4

In [21]:
#A unit cube (all sides are of unit length) is shown below. Determine the rotation matrix corresponding to rotation of the cube about its solid diagonal All by 90° in the counterclockwise direction. Determine the global coordinates of the vertex F after the rotation. Can we arrive at the same orientation (orientation obtained by rotating the cube about the solid diagonal All by 90°in the counterclockwise direction) by a combination of elementary rotations (Rotation about the coordinate axes)? If yes, mention the elementary rotations to be performed and their order. 

#globally coordinates of the vertex F
F = np.matrix([[1.0000],
                [1.0000],
                [1.0000]])

print("Position of the vertex F before rotation is :")
print(F)
print()

#rotation matrix corresponding to rotation of the cube about its solid diagonal All by 90° in the counterclockwise direction
R = np.matrix([[0.7071,-0.7071,0.0000],
                [0.7071,0.7071,0.0000],
                [0.0000,0.0000,1.0000]])
print("Rotation Matrix is :")
print(R)
print()

#global coordinates of the vertex F after the rotation
F1 = R*F
print("Position of the vertex F after rotation is :")
print(F1)

#rotation about the x-axis by 90° in the counterclockwise direction
R1 = np.matrix([[1.0000,0.0000,0.0000],
                [0.0000,0.0000,-1.0000],
                [0.0000,1.0000,0.0000]])

#rotation about the y-axis by 90° in the counterclockwise direction
R2 = np.matrix([[0.0000,0.0000,1.0000],
                [0.0000,1.0000,0.0000],
                [-1.0000,0.0000,0.0000]])

#rotation about the z-axis by 90° in the counterclockwise direction
R3 = np.matrix([[0.0000,-1.0000,0.0000],
                [1.0000,0.0000,0.0000],
                [0.0000,0.0000,1.0000]])

#rotation about the x-axis by 90° in the counterclockwise direction
R4 = np.matrix([[1.0000,0.0000,0.0000],
                [0.0000,0.0000,-1.0000],
                [0.0000,1.0000,0.0000]])

#coordinatess of the vertex F after the rotation
F2 = R1*R2*R3*R4*F
print("Position of the vertex F after doing elementry rotations is :")
print(F2)

Position of the vertex F before rotation is :
[[1.]
 [1.]
 [1.]]

Rotation Matrix is :
[[ 0.7071 -0.7071  0.    ]
 [ 0.7071  0.7071  0.    ]
 [ 0.      0.      1.    ]]

Position of the vertex F after rotation is :
[[0.    ]
 [1.4142]
 [1.    ]]
Position of the vertex F after doing elementry rotations is :
[[1.]
 [1.]
 [1.]]
